@echo off
rem
rem This file is generated by the Qt installer
rem

echo Setting up a Qt environment...

set QTDIR=C:\Qt\Qt5.1.0\5.1.0-beta1\msvc2010
echo -- QTDIR set to C:\Qt\Qt5.1.0\5.1.0-beta1\msvc2010
set PATH=C:\Qt\Qt5.1.0\5.1.0-beta1\msvc2010\bin;%PATH%
echo -- Added C:\Qt\Qt5.1.0\5.1.0-beta1\msvc2010\bin to PATH
set QMAKESPEC=win32-msvc2010
echo -- QMAKESPEC set to "win32-msvc2010"
set QTSRC=C:\Qt\Qt5.1.0\5.1.0-beta1\msvc2010
echo -- QTSRC set to C:\Qt\Qt5.1.0\5.1.0-beta1\msvc2010

call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" amd64